/** Public site config — never put secrets or private inbox here. */
export const site = {
  name: "Just One More",
  url: "https://justonemorestudio.vercel.app",
  instagram: "https://www.instagram.com/justonemore.exe/",
  quietblockDownload: "downloads/QuietBlock-1.0.0.zip",
  mascotImage: "models/mascotte.png",
  models3d: [
    { id: "mascotte", src: "models/mascotte.glb", poster: "models/mascotte.png", stats: [95, 80, 88] },
    { id: "demon", src: "models/demon_mascotte.glb", poster: "models/demon_mascotte.png", stats: [85, 90, 60] },
    { id: "dragon", src: "models/dragon_gamer.glb", poster: "models/dragon_gamer.png", stats: [75, 95, 40] },
    { id: "azure", src: "models/azure_guardian.glb", poster: "models/azure_guardian.png", stats: [80, 70, 30] },
    { id: "renard_hacker", src: "models/renard_hacker.glb", poster: "models/renard_hacker.png", stats: [90, 85, 75] },
    { id: "hibou_streamer", src: "models/hibou_streamer.glb", poster: "models/hibou_streamer.png", stats: [78, 88, 95] },
    { id: "robot_compagnon", src: "models/robot_compagnon.glb", poster: "models/robot_compagnon.png", stats: [70, 100, 3] },
    { id: "phenix_createur", src: "models/phenix_createur.glb", poster: "models/phenix_createur.png", stats: [100, 92, 55] },
    { id: "loup_indie", src: "models/loup_indie.glb", poster: "models/loup_indie.png", stats: [88, 65, 100] },
    { id: "chat_barista", src: "models/chat_barista.glb", poster: "models/chat_barista.png", stats: [82, 75, 100] },
    { id: "crimson_nocturne", src: "models/crimson_nocturne.glb", poster: "models/crimson_nocturne.png", stats: [92, 95, 12] },
    { id: "rat_business", src: "models/rat_business.glb", poster: "models/rat_business.png", stats: [72, 88, 45] },
    { id: "requin_costume", src: "models/requin_costume.glb", poster: "models/requin_costume.png", stats: [68, 92, 35] },
    { id: "singe_millionnaire", src: "models/singe_millionnaire.glb", poster: "models/singe_millionnaire.png", stats: [65, 78, 50] },
    { id: "fantome_entrepreneur", src: "models/fantome_entrepreneur.glb", poster: "models/fantome_entrepreneur.png", stats: [80, 55, 70] },
    { id: "canard_pdg", src: "models/canard_pdg.glb", poster: "models/canard_pdg.png", stats: [70, 60, 85] },
    { id: "chat_trader", src: "models/chat_trader.glb", poster: "models/chat_trader.png", stats: [55, 98, 100] },
    { id: "corbeau_mysterieux", src: "models/corbeau_mysterieux.glb", poster: "models/corbeau_mysterieux.png", stats: [88, 72, 40] },
    { id: "alien_curieux", src: "models/alien_curieux.glb", poster: "models/alien_curieux.png", stats: [95, 85, 20] },
    { id: "crocodile_riche", src: "models/crocodile_riche.glb", poster: "models/crocodile_riche.png", stats: [60, 75, 55] },
    { id: "requin_hoodie", src: "models/requin_hoodie.glb", poster: "models/requin_hoodie.png", stats: [78, 90, 65] },
    { id: "hamster_pression", src: "models/hamster_pression.glb", poster: "models/hamster_pression.png", stats: [75, 100, 100] },
    { id: "poulpe_multitache", src: "models/poulpe_multitache.glb", poster: "models/poulpe_multitache.png", stats: [85, 95, 80] },
    { id: "cochon_banquier", src: "models/cochon_banquier.glb", poster: "models/cochon_banquier.png", stats: [62, 70, 60] },
    { id: "grenouille_opportuniste", src: "models/grenouille_opportuniste.glb", poster: "models/grenouille_opportuniste.png", stats: [90, 82, 45] },
    { id: "blob_original", src: "models/blob_original.glb", poster: "models/blob_original.png", stats: [100, 70, 25] },
  ],
} as const
